name: Scraping UMiami Course Data

on: 
  schedule:
    - cron: "0 4 * * *" # Every day at 4 AM UTC (11 PM ET)
  workflow_dispatch:

env:
  MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.ATLAS_PUBLIC_API_KEY }}
  MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.ATLAS_PRIVATE_API_KEY }}
  MONGODB_ATLAS_PROJECT_ID: ${{ secrets.ATLAS_PROJECT_ID }}
  MONGO_URI: ${{ secrets.WEB_SCRAPER_MONGO_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository content
        uses: actions/checkout@v2
        
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r WebScraper/requirements.txt
          
      # Grant temporary MongoDB access to this Github Action runner ip address
      - name: Get the public IP of this runner
        id: get_gh_runner_ip
        shell: bash
        run: |
          echo "ip_address=$(curl https://checkip.amazonaws.com)" >> "$GITHUB_OUTPUT"
      - name: Setup MongoDB Atlas cli
        uses: mongodb/atlas-github-action@v0.2.0
      - name: Add runner IP to MongoDB access list
        shell: bash
        run: |
          atlas accessLists create ${{ steps.get_gh_runner_ip.outputs.ip_address }} --type ipAddress --projectId ${{ env.MONGODB_ATLAS_PROJECT_ID }} --comment  "Temporary access for GH Action"

      - name: First attempt to execute the python script
        id: first_attempt
        continue-on-error: true
        run: |
          python WebScraper/webScraper.py 2>&1 || true
          exit_code=$?
          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "Exit code: $exit_code"

      - name: Retry execution if first attempt failed
        if: steps.first_attempt.outputs.exit_code != '0'
        run: |
          python WebScraper/webScraper.py 2>&1

      - name: Remove GH runner IP from MongoDB access list
        if: always()
        shell: bash
        run: |
          atlas accessLists delete ${{ steps.get_gh_runner_ip.outputs.ip_address }} --projectId ${{ env.MONGODB_ATLAS_PROJECT_ID }} --force
